version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/tech_blog/gatsby
    steps:
      - checkout:
          path: ~/tech_blog
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v2-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v2-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v2-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Gatsby Build
          command: npm run build
      - run:
          name: Add ssh host
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Save wordpress admin panel
          command: ssh $SSH_USER@$SSH_HOST "cp -R /home/blueowlp/domains/techblog.com/public_html/admin /home/blueowlp/domains/techblog.com/tmp"
      - run:
          name: Save .htaccess
          command: ssh $SSH_USER@$SSH_HOST "cp -R /home/blueowlp/domains/techblog.com/public_html/.htaccess /home/blueowlp/domains/techblog.com/tmp"
      - run:
          name: Remove existing files
          command: ssh $SSH_USER@$SSH_HOST "rm -Rf /home/blueowlp/domains/techblog.com/public_html/*"
      - run:
          name: Restore wordpress admin panel
          command: ssh $SSH_USER@$SSH_HOST "mv /home/blueowlp/domains/techblog.com/tmp/admin /home/blueowlp/domains/techblog.com/public_html"
      - run:
          name: Restore .htaccess
          command: ssh $SSH_USER@$SSH_HOST "mv /home/blueowlp/domains/techblog.com/tmp/.htaccess /home/blueowlp/domains/techblog.com/public_html"
      - run:
          name: scp files
          command: scp -r public/* "$SSH_USER@$SSH_HOST:/home/blueowlp/domains/techblog.com/public_html/"
